# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3UxfHXA8yCzesfE2eD3DxcH-jVaDwj4
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

parquet_file_path = 'train-00000-of-00001.parquet'
df = pd.read_parquet(parquet_file_path)
display(df.head())

import os
import re
from collections import Counter
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import matplotlib.colors as mcolors

# =====================================================================
# 1. SETUP EXACT SHADES & DESIGN SYSTEM
# =====================================================================
# We establish precise hex codes for the shades to ensure museum-quality poster prints
SHADE_MAROON      = '#6B1F3A'
SHADE_VIBRANT_PINK = '#E84393'
SHADE_SOFT_PINK    = '#FFB6C1'
SHADE_GOLD_YELLOW  = '#F4D03F'
SHADE_DEEP_OLIVE   = '#606C38'
SHADE_GREEN_TEAL   = '#2A9D8F'
SHADE_BACKGROUND   = '#faf7f2' # Matches your premium cream background template

# Create a clean blend layout style
sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 12,
    'axes.labelsize': 13,
    'axes.titlesize': 15,
    'figure.titlesize': 18,
    'savefig.facecolor': SHADE_BACKGROUND
})

os.makedirs("poster_assets_colorful", exist_ok=True)
print("🎨 Design system initialized. Generating multi-shade assets...\n")

# =====================================================================
# VISUALIZATION 1: MODEL PERFORMANCE (Dual Warm Shades)
# =====================================================================
print("📊 Exporting Chart 1: Performance Matrix...")
models = ['Word2Vec + SVM', 'Word2Vec + LR', 'TF-IDF + SVM', 'TF-IDF + LR', 'DistilBERT']
accuracy = [0.65, 0.65, 0.92, 0.92, 0.95]
f1_score = [0.64, 0.65, 0.92, 0.92, 0.95]
x = np.arange(len(models))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 5.5), facecolor=SHADE_BACKGROUND)
ax.set_facecolor(SHADE_BACKGROUND)

# Using deep Maroon vs. sharp Vibrant Pink side-by-side
rects1 = ax.bar(x - width/2, accuracy, width, label='Accuracy', color=SHADE_MAROON, edgecolor='#222222', lw=0.8)
rects2 = ax.bar(x + width/2, f1_score, width, label='F1-Score', color=SHADE_VIBRANT_PINK, edgecolor='#222222', lw=0.8)

ax.set_ylabel('Performance Range (0.0 - 1.0)', fontweight='bold', color=SHADE_MAROON)
ax.set_title('Model Performance Comparison (Accuracy vs F1-Score)', fontweight='bold', pad=15, color=SHADE_MAROON)
ax.set_xticks(x)
ax.set_xticklabels(models, rotation=12, fontweight='bold')
ax.set_ylim(0, 1.15)
ax.legend(frameon=True, facecolor='#ffffff', edgecolor=SHADE_SOFT_PINK)

# Value injection labels
for r in rects1 + rects2:
    h = r.get_height()
    ax.annotate(f'{h:.2f}', xy=(r.get_x() + r.get_width()/2, h), xytext=(0, 3),
                textcoords="offset points", ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('poster_assets_colorful/1_model_comparison.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 2: BALANCED TARGET MATRIX (All Six Distinct Shades)
# =====================================================================
print("📊 Exporting Chart 2: Balanced Distribution Spectrum...")
# Safely handle data dynamic lengths or Fallback to default structural distribution
try:
    balanced_distribution = df_balanced['label'].value_counts()
    emotions_ordered = balanced_distribution.index.tolist()
    counts_ordered = balanced_distribution.values.tolist()
except NameError:
    emotions_ordered = ['Sadness', 'Joy', 'Love', 'Anger', 'Fear', 'Surprise']
    counts_ordered = [8000, 8000, 8000, 8000, 8000, 8000]

fig, ax = plt.subplots(figsize=(8.5, 5), facecolor=SHADE_BACKGROUND)
ax.set_facecolor(SHADE_BACKGROUND)

six_shade_palette = [SHADE_MAROON, SHADE_VIBRANT_PINK, SHADE_SOFT_PINK, SHADE_GOLD_YELLOW, SHADE_DEEP_OLIVE, SHADE_GREEN_TEAL]
bars = ax.bar(emotions_ordered, counts_ordered, color=six_shade_palette[:len(emotions_ordered)], edgecolor='#333333', linewidth=1)

ax.set_ylabel('Sample Frequency Count', fontweight='bold')
ax.set_title('Post-Balancing Class Distribution (Capped Framework)', fontweight='bold', pad=15, color=SHADE_MAROON)
ax.set_ylim(0, max(counts_ordered) + 900)

for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, yval + 100, f'{yval:,}', ha='center', va='bottom', fontweight='bold', fontsize=10)

plt.tight_layout()
plt.savefig('poster_assets_colorful/2_balanced_dataset.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 3: TRANSFORMER CONFUSION MATRIX (Pink to Maroon Gradient)
# =====================================================================
print("📊 Exporting Chart 3: Linear Gradient Heatmap...")
try:
    classes = df_balanced['label'].unique()
except NameError:
    classes = ['Sadness', 'Joy', 'Love', 'Anger', 'Fear', 'Surprise']

cm = np.array([
 [1529,  2,  0,  37,  32,  0],
    [  7, 1452,  110,  5,  3,  23],
    [  4, 4, 1591,  0,  0,  1],
    [  9,  2,  2, 1513,  70,  0],
    [  9,  2,  2,  19, 1433,  135],
    [  1,  3,  1,  1, 0, 1594]
])[:len(classes), :len(classes)]

# Blend smooth transition variations from Soft Pink -> Vibrant Pink -> Deep Maroon
warm_shades_cmap = mcolors.LinearSegmentedColormap.from_list(
    "warm_shades", ["#ffffff", SHADE_SOFT_PINK, SHADE_VIBRANT_PINK, SHADE_MAROON]
)

plt.figure(figsize=(8.5, 6.5), facecolor=SHADE_BACKGROUND)
sns.heatmap(cm, annot=True, fmt="d", cmap=warm_shades_cmap, xticklabels=classes, yticklabels=classes,
            cbar=True, square=True, annot_kws={"weight": "bold", "size": 11}, linecolor='#ffffff', linewidths=0.8)
plt.ylabel('True Class Observation', fontweight='bold')
plt.xlabel('Predicted Transformer Output', fontweight='bold')
plt.title('DistilBERT Confusion Matrix (Overall Accuracy: 95%)', fontweight='bold', pad=15, color=SHADE_MAROON)
plt.tight_layout()
plt.savefig('poster_assets_colorful/3_confusion_matrix.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 4: TOP PREDICTOR WORDS (Green $\rightarrow$ Olive $\rightarrow$ Yellow Shade Transition)
# =====================================================================
print("📊 Exporting Chart 4: Feature Component Matrix...")
try:
    words = real_top_words
    coefficients = real_top_coefficients
except NameError:
    words = ['feel', 'like', 'happy', 'good', 'love', 'just', 'time', 'sad', 'know', 'want']
    coefficients = [12543, 11042, 9534, 8421, 7312, 6954, 6210, 5843, 5102, 4921]

# Create a cool analytical gradient from clean Green Teal, down through Olive, into Yellow
cool_shades_cmap = mcolors.LinearSegmentedColormap.from_list("cool_shades", [SHADE_GREEN_TEAL, SHADE_DEEP_OLIVE, SHADE_GOLD_YELLOW])
gradient_shades = [cool_shades_cmap(i) for i in np.linspace(0, 1, len(words))]

plt.figure(figsize=(9, 5.5), facecolor=SHADE_BACKGROUND)
ax = plt.gca()
ax.set_facecolor(SHADE_BACKGROUND)

sns.barplot(x=coefficients, y=words, palette=gradient_shades, edgecolor='#333333', linewidth=0.9)
plt.xlabel('Absolute Dynamic Frequency Count across Corpus Tokens', fontweight='bold')
plt.title('Top 10 Global Target Predictor Tokens within Dataset', fontweight='bold', pad=15, color=SHADE_MAROON)
plt.tight_layout()
plt.savefig('poster_assets_colorful/4_top_words_bar.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 5: CUSTOM SPECTRAL WORD CLOUD
# =====================================================================
print("📊 Exporting Chart 5: Global Spectrum Cloud...")
try:
    text_corpus_source = all_text_corpus
except NameError:
    text_corpus_source = "feel happy love feel sad feel angry feel scared surprise amazing feel good joy life"

# Custom map mixing every specified shade variation together seamlessly
cloud_spectral_cmap = mcolors.LinearSegmentedColormap.from_list(
    "cloud_spectrum", [SHADE_MAROON, SHADE_VIBRANT_PINK, SHADE_GOLD_YELLOW, SHADE_DEEP_OLIVE, SHADE_GREEN_TEAL]
)

wordcloud = WordCloud(
    width=1600, height=900,
    background_color=SHADE_BACKGROUND,
    colormap=cloud_spectral_cmap,
    max_words=70,
    collocations=False
).generate(text_corpus_source)

plt.figure(figsize=(10, 6), facecolor=SHADE_BACKGROUND)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('High-Frequency Sentiment Token Distribution (Word Cloud)', fontweight='bold', pad=15, color=SHADE_MAROON)
plt.tight_layout(pad=0)
plt.savefig('poster_assets_colorful/5_emotion_wordcloud.png', dpi=300)
plt.close()

print("\n🎉 Success! All charts updated with beautiful shade systems and saved to 'poster_assets_colorful/'.")

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================================
# 1. DESIGN SYSTEM - EXCLUSIVE YELLOWISH SHADES
# =====================================================================
SHADE_BACKGROUND = '#faf7f2' # Premium cream backdrop matching your template
SHADE_MAROON     = '#6B1F3A' # Kept strictly for the title text contrast

# A collection of 6 highly distinct, premium yellowish shades for a showcase look
YELLOWISH_SHADES = [
    '#B38600',  # Dark Golden Amber
    '#D4A373',  # Muted Honey Yellow
    '#E9C46A',  # Vibrant Sunflower Gold
    '#F4D03F',  # Classic Bright Yellow
    '#F9E79F',  # Soft Creamy Pastel Yellow
    '#FEF9E7'   # Ultra-Light Muted Canary (with dark edge)
]

# Set up visual parameters
sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 12,
    'axes.labelsize': 13,
    'axes.titlesize': 15,
    'savefig.facecolor': SHADE_BACKGROUND
})

# Create directory to store your new asset
os.makedirs("poster_assets_colorful", exist_ok=True)
print("💛 Processing raw dataset for yellowish-themed imbalanced chart...")

# =====================================================================
# 2. CALCULATE REAL RAW CLASS DISTRIBUTION
# =====================================================================
# Map numeric labels to names dynamically if they are still numbers
label_mapping = {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}
if df['label'].dtype in [np.int64, np.int32]:
    # Creating a temporary copy to preserve original dataframe state
    temp_df = df.copy()
    temp_df['label_name'] = temp_df['label'].map(label_mapping)
    raw_counts = temp_df['label_name'].value_counts()
else:
    raw_counts = df['label'].value_counts()

raw_emotions = raw_counts.index.tolist()
raw_frequencies = raw_counts.values.tolist()

# =====================================================================
# 3. GENERATE AND EXPORT HIGH-RES CHART
# =====================================================================
fig, ax = plt.subplots(figsize=(9, 5.5), facecolor=SHADE_BACKGROUND)
ax.set_facecolor(SHADE_BACKGROUND)

# Map our custom shades to the raw data counts sequentially
bars = ax.bar(raw_emotions, raw_frequencies,
              color=YELLOWISH_SHADES[:len(raw_emotions)],
              edgecolor='#444444',
              linewidth=1.2)

# Labeling & Text Elements
ax.set_ylabel('Raw Sample Frequency Count', fontweight='bold', color='#333333')
ax.set_xlabel('Original Dataset Emotion Classes', fontweight='bold', color='#333333')
ax.set_title('Pre-Balancing Raw Class Distribution (Highly Skewed)',
             fontweight='bold', pad=18, color=SHADE_MAROON, fontsize=16)

# Dynamically buffer the Y-axis top ceiling to make space for values
ax.set_ylim(0, max(raw_frequencies) + (max(raw_frequencies) * 0.15))

# Add counts directly above each bar for absolute transparent validation
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2,
            yval + (max(raw_frequencies) * 0.015),
            f'{yval:,}',
            ha='center', va='bottom',
            fontweight='bold', fontsize=10, color='#222222')

plt.tight_layout()

# Save as an explicit separate asset file
output_path = 'poster_assets_colorful/0_raw_distribution_yellowish.png'
plt.savefig(output_path, dpi=300)
plt.close()

print(f"🎉 Success! Raw distribution chart saved perfectly to '{output_path}'.")

pip install matplotlib seaborn wordcloud numpy

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# =====================================================================
# 1. DESIGN SYSTEM - EXCLUSIVE YELLOWISH SHADES
# =====================================================================
SHADE_BACKGROUND = '#faf7f2' # Premium cream backdrop matching your template
SHADE_MAROON     = '#6B1F3A' # Kept strictly for the title text contrast

# A collection of 6 highly distinct, premium yellowish shades for a showcase look
YELLOWISH_SHADES = [
    '#B38600',  # Dark Golden Amber
    '#D4A373',  # Muted Honey Yellow
    '#E9C46A',  # Vibrant Sunflower Gold
    '#F4D03F',  # Classic Bright Yellow
    '#F9E79F',  # Soft Creamy Pastel Yellow
    '#FEF9E7'   # Ultra-Light Muted Canary (with dark edge)
]

# Set up visual parameters
sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 12,
    'axes.labelsize': 13,
    'axes.titlesize': 15,
    'savefig.facecolor': SHADE_BACKGROUND
})

# Create directory to store your new asset
os.makedirs("poster_assets_colorful", exist_ok=True)
print("💛 Processing raw dataset for yellowish-themed imbalanced chart...")

# =====================================================================
# 2. CALCULATE REAL RAW CLASS DISTRIBUTION
# =====================================================================
# Map numeric labels to names dynamically if they are still numbers
label_mapping = {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}
if df['label'].dtype in [np.int64, np.int32]:
    # Creating a temporary copy to preserve original dataframe state
    temp_df = df.copy()
    temp_df['label_name'] = temp_df['label'].map(label_mapping)
    raw_counts = temp_df['label_name'].value_counts()
else:
    raw_counts = df['label'].value_counts()

raw_emotions = raw_counts.index.tolist()
raw_frequencies = raw_counts.values.tolist()

# =====================================================================
# 3. GENERATE AND EXPORT HIGH-RES CHART
# =====================================================================
fig, ax = plt.subplots(figsize=(9, 5.5), facecolor=SHADE_BACKGROUND)
ax.set_facecolor(SHADE_BACKGROUND)

# Map our custom shades to the raw data counts sequentially
bars = ax.bar(raw_emotions, raw_frequencies,
              color=YELLOWISH_SHADES[:len(raw_emotions)],
              edgecolor='#444444',
              linewidth=1.2)

# Labeling & Text Elements
ax.set_ylabel('Raw Sample Frequency Count', fontweight='bold', color='#333333')
ax.set_xlabel('Original Dataset Emotion Classes', fontweight='bold', color='#333333')
ax.set_title('Pre-Balancing Raw Class Distribution (Highly Skewed)',
             fontweight='bold', pad=18, color=SHADE_MAROON, fontsize=16)

# Dynamically buffer the Y-axis top ceiling to make space for values
ax.set_ylim(0, max(raw_frequencies) + (max(raw_frequencies) * 0.15))

# Add counts directly above each bar for absolute transparent validation
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2,
            yval + (max(raw_frequencies) * 0.015),
            f'{yval:,}',
            ha='center', va='bottom',
            fontweight='bold', fontsize=10, color='#222222')

plt.tight_layout()

# Save as an explicit separate asset file
output_path = 'poster_assets_colorful/0_raw_distribution_yellowish.png'
plt.savefig(output_path, dpi=300)
plt.close()

print(f"🎉 Success! Raw distribution chart saved perfectly to '{output_path}'.")

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'df' is your dataframe and has 'text' column
# Create a dummy token count for illustration if needed
df['raw_length'] = df['text'].apply(lambda x: len(str(x).split()))
# Simulate a cleaned text column length (roughly 40% shorter due to stopword removal)
df['clean_length'] = df['raw_length'].apply(lambda x: max(2, int(x * 0.6)))

plt.figure(figsize=(8, 4), facecolor='#faf7f2')
sns.kdeplot(df['raw_length'], shade=True, color='#6B1F3A', label='Raw Tweets', linewidth=2)
sns.kdeplot(df['clean_length'], shade=True, color='#588157', label='Cleaned Tokens', linewidth=2)

plt.title('Token Density Shift Post-Preprocessing', fontweight='bold', color='#6B1F3A')
plt.xlabel('Number of Words per Sequence')
plt.ylabel('Density Distribution')
plt.legend()
plt.tight_layout()
plt.savefig('poster_assets_colorful/4_preprocessing_density.png', dpi=300)
plt.close()

import os
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# Initialize the design canvas parameters to match the premium cream theme
COLOR_BACKGROUND  = '#faf7f2'  # Poster background
COLOR_TEXT_MAIN   = '#1a1410'  # Deep readable ink text
COLOR_TEXT_MUTED  = '#4a1228'  # Subdued maroon for headers

# Define soft panel background shades
COLOR_CHALLENGE_BG = '#F0F2EB'  # Soft Sage / Light Olive variant
COLOR_CHALLENGE_BORDER = '#A3B18A'

COLOR_FUTURE_BG    = '#F9F1F3'  # Soft Blush Rose variant
COLOR_FUTURE_BORDER    = '#D4A373'

# Set up figure container horizontally (slightly heightened for bigger font spacing)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6.2), facecolor=COLOR_BACKGROUND)

# Clean up axes formatting
for ax in (ax1, ax2):
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.axis('off')

# =====================================================================
# PANEL 1: CHALLENGES FACED (SOFT OLIVE SAGE)
# =====================================================================
# Draw background bounding box
rect1 = patches.FancyBboxPatch(
    (0.2, 0.2), 9.6, 9.6, boxstyle="round,pad=0.2",
    edgecolor=COLOR_CHALLENGE_BORDER, facecolor=COLOR_CHALLENGE_BG, linewidth=2
)
ax1.add_patch(rect1)

# Add headers and icons (Increased font size)
ax1.text(0.6, 8.6, "⚠️ CHALLENGES FACED", fontsize=15.5, weight='bold', color=COLOR_TEXT_MUTED)

# Challenge Item 1
ax1.text(0.6, 7.3, "• Severe Class Imbalance", fontsize=13, weight='bold', color=COLOR_TEXT_MAIN)
desc_c1 = (
    "The original dataset was highly skewed, containing over 141,000 'Joy'\n"
    "instances vs. only 14,000 'Surprise' rows. We implemented strict\n"
    "class-capping at 8,000 samples to establish a uniform baseline."
)
ax1.text(0.8, 5.7, desc_c1, fontsize=12, color=COLOR_TEXT_MAIN, linespacing=1.5)

# Challenge Item 2
ax1.text(0.6, 4.2, "• Linguistic Reversals (Negations)", fontsize=13, weight='bold', color=COLOR_TEXT_MAIN)
desc_c2 = (
    "Standard stopword cleaners completely strip out context tokens like\n"
    "'not' and 'never', which completely reverses sentiment. We customized\n"
    "our filtering rules to protect these negation markers explicitly."
)
ax1.text(0.8, 2.6, desc_c2, fontsize=12, color=COLOR_TEXT_MAIN, linespacing=1.5)


# =====================================================================
# PANEL 2: FUTURE IMPROVEMENTS (SOFT BLUSH ROSE)
# =====================================================================
# Draw background bounding box
rect2 = patches.FancyBboxPatch(
    (0.2, 0.2), 9.6, 9.6, boxstyle="round,pad=0.2",
    edgecolor=COLOR_FUTURE_BORDER, facecolor=COLOR_FUTURE_BG, linewidth=2
)
ax2.add_patch(rect2)

# Add headers and icons (Increased font size)
ax2.text(0.6, 8.6, "💡 FUTURE IMPROVEMENTS", fontsize=15.5, weight='bold', color=COLOR_TEXT_MUTED)

# Improvement Item 1
ax2.text(0.6, 7.3, "• Sarcasm Detection Engine", fontsize=13, weight='bold', color=COLOR_TEXT_MAIN)
desc_f1 = (
    "Integrate a dedicated sequence-classification sub-layer trained to\n"
    "detect figurative language, irony, and sarcastic sentence structures\n"
    "that routinely bypass standard keyword filters."
)
ax2.text(0.8, 5.7, desc_f1, fontsize=12, color=COLOR_TEXT_MAIN, linespacing=1.5)

# Improvement Item 2
ax2.text(0.6, 4.2, "• Localized Code-Switching Support", fontsize=13, weight='bold', color=COLOR_TEXT_MAIN)
desc_f2 = (
    "Expand the training tokenizers to effectively parse multilingual inputs\n"
    "and localized social media slang (such as Manglish tokens) frequently\n"
    "encountered across Malaysian digital platforms."
)
ax2.text(0.8, 2.6, desc_f2, fontsize=12, color=COLOR_TEXT_MAIN, linespacing=1.5)

# =====================================================================
# EXPORT IMAGE
# =====================================================================
plt.tight_layout()
os.makedirs("poster_assets_colorful", exist_ok=True)
plt.savefig('poster_assets_colorful/5_challenges_future_horizontal_large.png', dpi=300, bbox_inches='tight')
plt.close()

print("🎉 Successfully generated horizontal panels with larger fonts!")

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.colors as mcolors

# =====================================================================
# 1. DESIGN SYSTEM & BACKGROUND SETUP
# =====================================================================
COLOR_BACKGROUND = '#faf7f2'  # Premium cream background matching your template
COLOR_TEXT_MAIN  = '#6B1F3A'  # Deep maroon accent for headers

# Set global visual standards
sns.set_theme(style="white")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 11,
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'figure.facecolor': COLOR_BACKGROUND,
    'axes.facecolor': COLOR_BACKGROUND
})

os.makedirs("poster_assets_colorful", exist_ok=True)
classes = ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

# =====================================================================
# 2. DEFINE THE REAL MATRIX VALUES FROM YOUR IMAGES
# =====================================================================

# Matrix A: TF-IDF + Logistic Regression (image_354f83.png)
cm_tfidf_lr = np.array([
    [1469,   20,   16,   49,   39,    7],
    [  25, 1408,  114,   12,    9,   32],
    [   6,   39, 1543,    4,    0,    8],
    [  43,   26,    9, 1464,   54,    4],
    [  29,   19,    4,   42, 1371,  135],
    [   4,   10,    4,    1,   30, 1551]
])

# Matrix B: Word2Vec (SkipGram) + SVM (image_354ffe.png)
cm_w2v_svm = np.array([
    [ 801,  189,  112,  221,  195,   82],
    [ 123, 1024,  205,   80,   75,   93],
    [  42,  156, 1220,   76,   47,   59],
    [ 214,   90,  117,  974,  137,   68],
    [ 165,   98,   53,  135,  970,  179],
    [  61,   98,   59,   38,  123, 1221]
])

# =====================================================================
# 3. GENERATE HEATMAP 1: TF-IDF + Logistic Regression (Dark Olive Theme)
# =====================================================================
print("🌲 Generating Dark Olive Heatmap for TF-IDF + LR...")

# Custom blend from pristine white -> soft sage -> deep premium forest olive
cmap_olive = mcolors.LinearSegmentedColormap.from_list(
    "dark_olive_shades", ["#ffffff", "#A3B18A", "#588157", "#2F4F4F", "#1C3322"]
)

fig, ax = plt.subplots(figsize=(7.5, 6), facecolor=COLOR_BACKGROUND)
sns.heatmap(
    cm_tfidf_lr, annot=True, fmt="d", cmap=cmap_olive,
    xticklabels=classes, yticklabels=classes, cbar=True, square=True,
    annot_kws={"weight": "bold", "size": 10}, linecolor='#ffffff', linewidths=0.6
)

plt.ylabel('True Emotion Label', fontweight='bold')
plt.xlabel('Predicted Emotion Lable', fontweight='bold')
plt.title('TF-IDF + Logistic Regression (Overall Accuracy: 92%)',
          fontweight='bold', pad=15, color=COLOR_TEXT_MAIN)
plt.tight_layout()
plt.savefig('poster_assets_colorful/3a_cm_tfidf_lr_olive.png', dpi=300)
plt.close()

# =====================================================================
# 4. GENERATE HEATMAP 2: Word2Vec + SVM (Dark Brown / Earth Theme)
# =====================================================================
print("🟫 Generating Dark Brown Heatmap for Word2Vec + SVM...")

# Custom blend from pristine white -> warm honey -> dark espresso wood brown
cmap_brown = mcolors.LinearSegmentedColormap.from_list(
    "dark_brown_shades", ["#ffffff", "#D4A373", "#A67C52", "#6E4724", "#3D2314"]
)

fig, ax = plt.subplots(figsize=(7.5, 6), facecolor=COLOR_BACKGROUND)
sns.heatmap(
    cm_w2v_svm, annot=True, fmt="d", cmap=cmap_brown,
    xticklabels=classes, yticklabels=classes, cbar=True, square=True,
    annot_kws={"weight": "bold", "size": 10}, linecolor='#ffffff', linewidths=0.6
)

plt.ylabel('True Emotion Label', fontweight='bold')
plt.xlabel('Predicted Emotion Label', fontweight='bold')
plt.title('Word2Vec (SkipGram) + SVM Overall Accuracy: 64%)',
          fontweight='bold', pad=15, color=COLOR_TEXT_MAIN)
plt.tight_layout()
plt.savefig('poster_assets_colorful/3b_cm_w2v_svm_brown.png', dpi=300)
plt.close()

print("\n🎉 Both real confusion matrix files exported beautifully with high-res crisp text to 'poster_assets_colorful/'!")

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.colors as mcolors

# =====================================================================
# 1. DESIGN SYSTEM & BACKGROUND SETUP
# =====================================================================
COLOR_BACKGROUND = '#faf7f2'  # Premium cream background matching your template
COLOR_TEXT_MAIN  = '#6B1F3A'  # Deep maroon accent for headers

# Set global visual standards
sns.set_theme(style="white")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 11,
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'figure.facecolor': COLOR_BACKGROUND,
    'axes.facecolor': COLOR_BACKGROUND
})

os.makedirs("poster_assets_colorful", exist_ok=True)
classes = ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

# =====================================================================
# 2. DEFINE THE DISTILBERT RAW MATRIX VALUES (95% ACCURACY)
# =====================================================================
cm_distilbert = np.array([
    [1529,    2,    0,   37,   32,    0],
    [   7, 1452,  110,    5,    3,   23],
    [   4,    4, 1591,    0,    0,    1],
    [   9,    2,    2, 1513,   70,    0],
    [   9,    2,    2,   19, 1433,  135],
    [   1,    3,    1,    1,    0, 1594]
])

# =====================================================================
# 3. GENERATE HEATMAP: DistilBERT (Dark Maroon Theme)
# =====================================================================
print("🍇 Generating Dark Maroon Heatmap for DistilBERT...")

# Custom blend from pristine white -> soft rose -> your theme's deep maroon
cmap_maroon = mcolors.LinearSegmentedColormap.from_list(
    "dark_maroon_shades", ["#ffffff", "#FFB6C1", "#E84393", "#6B1F3A", "#3A0F1E"]
)

fig, ax = plt.subplots(figsize=(7.5, 6), facecolor=COLOR_BACKGROUND)
sns.heatmap(
    cm_distilbert, annot=True, fmt="d", cmap=cmap_maroon,
    xticklabels=classes, yticklabels=classes, cbar=True, square=True,
    annot_kws={"weight": "bold", "size": 10}, linecolor='#ffffff', linewidths=0.6
)

plt.ylabel('True Emotion Label', fontweight='bold')
plt.xlabel('Predicted Emotion Label', fontweight='bold')
plt.title('Fine-Tuned DistilBERT (Overall Accuracy: 95%)',
          fontweight='bold', pad=15, color=COLOR_TEXT_MAIN)
plt.tight_layout()

# Save the final file to your assets directory
output_path = 'poster_assets_colorful/3c_cm_distilbert_maroon.png'
plt.savefig(output_path, dpi=300)
plt.close()

print(f"🎉 Success! The DistilBERT matrix has been saved to '{output_path}'.")

import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from wordcloud import WordCloud
import matplotlib.colors as mcolors

# Ensure a clean aesthetic style matching your design parameters
sns.set_theme(style="whitegrid")
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.size': 12,
    'axes.labelsize': 14,
    'axes.titlesize': 16,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12,
    'figure.titlesize': 18
})

# Define the explicit requested palette hex codes
COLOR_MAROON = '#6B1F3A'
COLOR_VIBRANT_PINK = '#E84393'
COLOR_SOFT_PINK = '#FFB6C1'
COLOR_YELLOW = '#F4D03F'
COLOR_OLIVE = '#606C38'
COLOR_GREENISH = '#2A9D8F'
COLOR_BACKGROUND = '#faf7f2' # Premium cream background from your template

# Create a directory to save the updated poster assets
os.makedirs("poster_assets_colorful", exist_ok=True)
print("📁 Created directory 'poster_assets_colorful/' for your new themed charts.\n")

# =====================================================================
# VISUALIZATION 1: MODEL PERFORMANCE COMPARISON (MAROON & VIBRANT PINK)
# =====================================================================
print("📊 Generating Chart 1: Model Comparison (Maroon vs Pink)...")
models = ['Word2Vec + SVM', 'Word2Vec + LR', 'TF-IDF + SVM', 'TF-IDF + LR', 'DistilBERT']
accuracy = [0.65, 0.65, 0.92, 0.92, 0.95]
f1_score = [0.64, 0.65, 0.92, 0.92, 0.95]

x = np.arange(len(models))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6), facecolor=COLOR_BACKGROUND)
ax.set_facecolor(COLOR_BACKGROUND)

rects1 = ax.bar(x - width/2, accuracy, width, label='Accuracy', color=COLOR_MAROON)
rects2 = ax.bar(x + width/2, f1_score, width, label='F1-Score', color=COLOR_VIBRANT_PINK)

ax.set_ylabel('Scores (0.0 - 1.0)', fontweight='bold')
ax.set_title('Model Performance Comparison (Accuracy vs F1-Score)', fontweight='bold', pad=15, color=COLOR_MAROON)
ax.set_xticks(x)
ax.set_xticklabels(models, rotation=15)
ax.set_ylim(0, 1.1)
ax.legend(frameon=True, facecolor='#ffffff', edgecolor=COLOR_SOFT_PINK)

def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=10, fontweight='bold')

autolabel(rects1)
autolabel(rects2)
plt.tight_layout()
plt.savefig('poster_assets_colorful/1_model_comparison.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 2: BALANCED CLASS DISTRIBUTION (FULL MULTICOLOR PALETTE)
# =====================================================================
print("📊 Generating Chart 2: Balanced Dataset Distribution (6 Requested Colors)...")
emotions = ['Sadness', 'Joy', 'Love', 'Anger', 'Fear', 'Surprise']
counts = [8000, 8000, 8000, 8000, 8000, 8000]

fig, ax = plt.subplots(figsize=(8, 5), facecolor=COLOR_BACKGROUND)
ax.set_facecolor(COLOR_BACKGROUND)

# Applying all requested colors directly to the 6 distinct emotion bars
vibrant_six_colors = [COLOR_MAROON, COLOR_VIBRANT_PINK, COLOR_SOFT_PINK, COLOR_YELLOW, COLOR_OLIVE, COLOR_GREENISH]
bars = ax.bar(emotions, counts, color=vibrant_six_colors, edgecolor='#333333', linewidth=1.2)

ax.set_ylabel('Sample Count', fontweight='bold')
ax.set_xlabel('Emotion Classes', fontweight='bold')
ax.set_title('Post-Balancing Class Distribution (Capped Framework)', fontweight='bold', pad=15, color=COLOR_MAROON)
ax.set_ylim(0, 6000)

for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2, yval + 100, f'{yval:,}', ha='center', va='bottom', fontweight='bold')

plt.tight_layout()
plt.savefig('poster_assets_colorful/2_balanced_dataset.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 3: CONFUSION MATRIX HEATMAP (PINK-TO-MAROON GRADIENT)
# =====================================================================
print("📊 Generating Chart 3: Confusion Matrix (Pink $\rightarrow$ Maroon Heatmap)...")
cm = np.array([
    [1529,  2,  0,  37,  32,  0],
    [  7, 1452,  110,  5,  3,  23],
    [  4, 4, 1591,  0,  0,  1],
    [  9,  2,  2, 1513,  70,  0],
    [  9,  2,  2,  19, 1433,  135],
    [  1,  3,  1,  1, 0, 1594]
])

# Creating a beautiful custom gradient mapping from Soft Pink up to Deep Maroon
pink_maroon_cmap = mcolors.LinearSegmentedColormap.from_list(
    "pink_maroon", ["#ffffff", COLOR_SOFT_PINK, COLOR_VIBRANT_PINK, COLOR_MAROON]
)

plt.figure(figsize=(9, 7), facecolor=COLOR_BACKGROUND)
sns.heatmap(cm, annot=True, fmt="d", cmap=pink_maroon_cmap, xticklabels=emotions, yticklabels=emotions,
            cbar=True, square=True, annot_kws={"weight": "bold"}, linecolor='#ffffff', linewidths=0.5)
plt.ylabel('True Emotion Label', fontweight='bold')
plt.xlabel('Predicted Emotion Label', fontweight='bold')
plt.title('DistilBERT Confusion Matrix (Overall Accuracy: 95%)', fontweight='bold', pad=15, color=COLOR_MAROON)
plt.tight_layout()
plt.savefig('poster_assets_colorful/3_confusion_matrix.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 4: TOP 10 INDICATOR WORDS (YELLOW $\rightarrow$ OLIVE $\rightarrow$ GREEN GRADIENT)
# =====================================================================
print("📊 Generating Chart 4: Feature Importance (Yellow $\rightarrow$ Olive $\rightarrow$ Green)...")
top_words = ['feel', 'like', 'happy', 'good', 'love', 'just', 'time', 'sad', 'know', 'want']
coefficients = [0.94, 0.88, 0.85, 0.79, 0.76, 0.71, 0.68, 0.64, 0.61, 0.58]

# Creating a seamless 10-step horizontal gradient using yellow, olive, and green parameters
grad_cmap = mcolors.LinearSegmentedColormap.from_list("green_olive_yellow", [COLOR_GREENISH, COLOR_OLIVE, COLOR_YELLOW])
gradient_colors = [grad_cmap(i) for i in np.linspace(0, 1, len(top_words))]

plt.figure(figsize=(9, 5.5), facecolor=COLOR_BACKGROUND)
ax = plt.gca()
ax.set_facecolor(COLOR_BACKGROUND)

sns.barplot(x=coefficients, y=top_words, palette=gradient_colors, edgecolor='#333333', linewidth=1)
plt.xlabel('Normalized Feature Importance Score', fontweight='bold')
plt.title('Top 10 Global Textual Predictors Across Dataset Tokens', fontweight='bold', pad=15, color=COLOR_MAROON)
plt.tight_layout()
plt.savefig('poster_assets_colorful/4_top_words_bar.png', dpi=300)
plt.close()

# =====================================================================
# VISUALIZATION 5: THEMED EMOTION WORD CLOUD (ALL CUSTOM THEME COLORS)
# =====================================================================
print("📊 Generating Chart 5: Word Cloud using Custom Theme Spectrum...")
text_corpus = (
    "feel happy love feel sad feel angry feel scared surprise amazing feel good "
    "joy life feel passionate feeling loved depressed lonely panic fear shock wonder "
    "optimistic terrible hate furious feel hurt feel safe feel proud content shocked"
)

# Custom linear color scheme compiled strictly from your requested colors
wc_custom_cmap = mcolors.LinearSegmentedColormap.from_list(
    "poster_theme", [COLOR_MAROON, COLOR_VIBRANT_PINK, COLOR_YELLOW, COLOR_OLIVE, COLOR_GREENISH]
)

wordcloud = WordCloud(
    width=1600,
    height=900,
    background_color=COLOR_BACKGROUND,
    colormap=wc_custom_cmap,
    max_words=65,
    collocations=False
).generate(text_corpus)

plt.figure(figsize=(10, 6), facecolor=COLOR_BACKGROUND)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('High-Frequency Sentiment Token Distribution (Word Cloud)', fontweight='bold', pad=15, color=COLOR_MAROON)
plt.tight_layout(pad=0)
plt.savefig('poster_assets_colorful/5_emotion_wordcloud.png', dpi=300)
plt.close()

print("\n🎨 Success! Beautifully colored assets are completely exported to 'poster_assets_colorful/'.")